run:
    image: python:3.5-alpine
    script:
    - echo $K8S_SECRET_POD_FEEDER_TEST_POD
    - echo $CI_JOB_ID
    - pip3 install -r requirements.txt
    - ./pod_feeder.py
        --pod-url   $K8S_SECRET_POD_FEEDER_TEST_POD
        --username  $K8S_SECRET_POD_FEEDER_TEST_USER
        --password  $K8S_SECRET_POD_FEEDER_TEST_PASSWORD
        --aspect-id $K8S_SECRET_POD_FEEDER_TEST_ASPECT_ID
        --database feed.db
        --feed-id test
        --feed-url https://www.eff.org/rss/updates.xml
        --auto-tag foo
        --auto-tag bar
        --ignore-tag bar
        --category-tags
        --summary
        --via gitlb-ci
        --limit 1
        --debug
    - ./clean_db.py feed.db
