image: python:3.5

stages:
  - test
  - build
  - upload

formatting:
    stage: test
    image: python:alpine
    allow_failure: true
    script:
    - pip3 install -q black
    - black --check .

unittest:
    image: python:latest
    stage: test
    script:
    - pip3 install -r requirements.txt -q
    - python3 -m unittest

run:
    stage: test
    script:
    - pip3 install -r requirements.txt -q
    - pod_feeder_v2/pod_feeder.py
        --pod-url   $POD_FEEDER_TEST_POD
        --username  $POD_FEEDER_TEST_USER
        --password  $POD_FEEDER_TEST_PASSWORD
        --aspect-id $POD_FEEDER_TEST_ASPECT_ID
        --database feed.db
        --feed-id eff
        --feed-url https://www.eff.org/rss/updates.xml
        --auto-tag foo
        --auto-tag bar
        --ignore-tag bar
        --category-tags
        --embed-image
        --summary
        --via gitlb-ci
        --limit 1
        --debug
    - pod_feeder_v2/pod_feeder.py
        --pod-url   $POD_FEEDER_TEST_POD
        --username  $POD_FEEDER_TEST_USER
        --password  $POD_FEEDER_TEST_PASSWORD
        --aspect-id $POD_FEEDER_TEST_ASPECT_ID
        --database feed.db
        --feed-id gitlab
        --feed-url $CI_PROJECT_URL/commits/$CI_COMMIT_REF_NAME?format=atom
        --embed-image
        --full
        --limit 1
        --debug
    - pod_feeder_v2/clean_db.py feed.db

build_package:
    stage: build
    only:
      - tags
    script:
    - python3 -m pip install --user --upgrade setuptools wheel
    - python3 setup.py sdist bdist_wheel
    artifacts:
      paths:
      - dist/
      expire_in: 1 year

upload_package:
    stage: upload
    only:
      - tags
    script:
    - python3 -m pip install --user --upgrade setuptools twine wheel
    - python3 -m twine upload dist/*

include:
  template: Dependency-Scanning.gitlab-ci.yml
